-- ORDER V1: Supabase database setup
-- Run this entire script in Supabase SQL Editor.

create table if not exists public.order_datasets (
  id bigint generated by default as identity primary key,
  file_name text not null default 'ORDER',
  headers jsonb not null default '[]'::jsonb,
  rows jsonb not null default '[]'::jsonb,
  row_count integer not null default 0,
  saved_at timestamptz not null default now()
);

create index if not exists order_datasets_saved_at_idx
  on public.order_datasets (saved_at desc);

-- New Supabase projects may require explicit Data API grants.
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on table public.order_datasets to anon, authenticated;
grant usage, select on sequence public.order_datasets_id_seq to anon, authenticated;

alter table public.order_datasets enable row level security;

drop policy if exists "order_datasets_select" on public.order_datasets;
drop policy if exists "order_datasets_insert" on public.order_datasets;
drop policy if exists "order_datasets_update" on public.order_datasets;
drop policy if exists "order_datasets_delete" on public.order_datasets;

create policy "order_datasets_select"
on public.order_datasets for select
to anon, authenticated
using (true);

create policy "order_datasets_insert"
on public.order_datasets for insert
to anon, authenticated
with check (true);

create policy "order_datasets_update"
on public.order_datasets for update
to anon, authenticated
using (true)
with check (true);

create policy "order_datasets_delete"
on public.order_datasets for delete
to anon, authenticated
using (true);
